In [115]:
import openai
import pandas as pd
import json
import ast

class ChatGptFakeDataGenerator:
    def __init__(self, features_list,rows_number,openai_key):
        self.features_list = features_list
        self.rows_number=rows_number
        self.openai_key=openai_key
        self.df=None
        self.generate_data()

    def get_dataframe(self):
        return self.df
            
    def get_json(self):
        return self.df.to_json()
    
    def generate_data(self):
        data_list = []
        try:
            openai.api_key = self.openai_key
            basic_query= "fake data for"+ str(self.rows_number)+ "rows with the features of "+str(self.features_list)+" in a key-value data structure format"
            answer = openai.ChatCompletion.create(model='gpt-3.5-turbo', messages=[{'role': 'user', 'content': basic_query}])
            answer = answer['choices'][0]['message']['content'].replace('\n', '')
            answer_dict=ast.literal_eval(answer)
            self.df= pd.DataFrame.from_dict(answer_dict)
            
        except:
               print("We cannot generate the data check your inputs!")

In [116]:
features_list=["first_name","last_name","age","adress","country",'scool name',"salary","favorite animal"]
rows_number=50
key_="my API key is already in the 'key' variable"
generator= ChatGptFakeDataGenerator(features_list,rows_number,key)

In [118]:
# sometimes you have to add the transpose to have the correct form of dataframe
generator.get_dataframe().T

,first_name,last_name,age,address,country,school name,salary,favorite animal
1,Emily,Johnson,28,123 Main St,USA,Central High School,55000,Dog
2,Oliver,Smith,42,456 Oak Ln,Canada,North High School,66000,Cat
3,Isabella,Brown,35,789 Elm St,USA,South High School,72000,Elephant
4,William,Taylor,56,321 Maple Ave,Australia,West High School,82000,Giraffe
5,Sophia,Garcia,24,654 Pine Rd,USA,East High School,47000,Turtle
6,Mason,Martinez,31,987 Oak St,Canada,Northwest High School,59000,Lion
7,Emma,Anderson,49,159 Maple St,USA,Northeast High School,88000,Dog
8,Jacob,Thomas,19,753 Pine St,Australia,Southeast High School,30000,Monkey
9,Ava,Lee,38,258 Elm St,Canada,Southwest High School,67000,Penguin
10,Noah,Gonzalez,27,456 Oak Ln,USA,Central High School,59000,Dolphin
11,Charlotte,Hernandez,43,753 Pine St,Australia,North High School,75000,Horse
12,Ethan,Moore,34,321 Maple Ave,Canada,East High School,62000,Giraffe
13,Luna,Jackson,29,789 Elm St,USA,West High School,56000,Koala
14,Liam,Martin,21,654 Pine Rd,Canada,Northwest High School,42000,Panda
15,Avery,Thompson,47,987 Oak St,USA,Southeast High School,88000,Tiger
16,Logan,White,33,159 Maple St,Australia,Northeast High School,67000,Elephant
17,Chloe,Allen,50,753 Pine St,Canada,Southwest High School,93000,Dolphin
18,James,Wright,25,258 Elm St,USA,Central High School,55000,Lion
19,Grace,King,36,456 Oak Ln,Australia,East High School,71000,Penguin
20,Alexander,Scott,52,321 Maple Ave,Canada,Northwest High School,78000,Gorilla
21,Hazel,Green,48,789 Elm St,USA,West High School,84000,Kangaroo
22,Benjamin,Baker,39,654 Pine Rd,Canada,Southeast High School,63000,Panda
23,Sofia,Nelson,22,987 Oak St,USA,Northeast High School,48000,Turtle
24,Michael,Williams,19,159 Maple St,Australia,Southwest High School,30000,Koala
25,Madison,Jones,44,753 Pine St,USA,Central High School,76000,Monkey
26,Daniel,Davis,30,258 Elm St,Canada,North High School,57000,Tiger
27,Claire,Rodriguez,37,456 Oak Ln,Australia,East High School,69000,Giraffe
28,Miles,Parker,26,789 Elm St,USA,West High School,54000,Penguin
29,Audrey,Gomez,24,321 Maple Ave,Canada,Northwest High School,50000,Lion
30,Henry,Cruz,41,654 Pine Rd,USA,Southeast High School,65000,Dolphin
31,Penelope,Collins,32,987 Oak St,Australia,Northeast High School,75000,Gorilla
32,Sebastian,Perez,28,159 Maple St,Canada,Southwest High School,61000,Elephant
33,Ella,Turner,33,753 Pine St,USA,Central High School,62000,Turtle
34,Jacob,Adams,49,258 Elm St,Australia,North High School,91000,Panda
35,Mia,Campbell,23,456 Oak Ln,Canada,East High School,48000,Tiger
36,William,Mitchell,40,789 Elm St,USA,West High School,67000,Kangaroo
37,Victoria,Parker,28,321 Maple Ave,Australia,Northwest High School,57000,Monkey
38,Owen,Evans,31,654 Pine Rd,Canada,Southeast High School,52000,Gorilla
39,Natalie,Edwards,47,987 Oak St,USA,Northeast High School,83000,Penguin
40,Carter,Collins,19,159 Maple St,Australia,Southwest High School,32000,Lion
41,Scarlett,Stewart,44,753 Pine St,USA,Central High School,80000,Dolphin
42,Gabriel,Sanchez,25,258 Elm St,Canada,North High School,51000,Giraffe
43,Aria,Morales,30,456 Oak Ln,Australia,East High School,63000,Kangaroo
44,Jackson,Roach,39,789 Elm St,USA,West High School,75000,Tiger
45,Amelia,Bush,21,321 Maple Ave,Canada,Northwest High School,41000,Turtle
46,Elijah,Knight,35,654 Pine Rd,USA,Southeast High School,72000,Elephant
47,Leah,Hudson,46,987 Oak St,Australia,Northeast High School,81000,Lion
48,William,Roberts,33,159 Maple St,Canada,Southwest High School,60000,Panda
49,Aaliyah,Drake,29,753 Pine St,USA,Central High School,57000,Gorilla
50,Oliver,Reyes,26,258 Elm St,Australia,North High School,48000,Penguin

In [119]:
generator.get_json()

'{"1":{"first_name":"Emily","last_name":"Johnson","age":28,"address":"123 Main St","country":"USA","school name":"Central High School","salary":55000,"favorite animal":"Dog"},"2":{"first_name":"Oliver","last_name":"Smith","age":42,"address":"456 Oak Ln","country":"Canada","school name":"North High School","salary":66000,"favorite animal":"Cat"},"3":{"first_name":"Isabella","last_name":"Brown","age":35,"address":"789 Elm St","country":"USA","school name":"South High School","salary":72000,"favorite animal":"Elephant"},"4":{"first_name":"William","last_name":"Taylor","age":56,"address":"321 Maple Ave","country":"Australia","school name":"West High School","salary":82000,"favorite animal":"Giraffe"},"5":{"first_name":"Sophia","last_name":"Garcia","age":24,"address":"654 Pine Rd","country":"USA","school name":"East High School","salary":47000,"favorite animal":"Turtle"},"6":{"first_name":"Mason","last_name":"Martinez","age":31,"address":"987 Oak St","country":"Canada","school name":"Northwest High School","salary":59000,"favorite animal":"Lion"},"7":{"first_name":"Emma","last_name":"Anderson","age":49,"address":"159 Maple St","country":"USA","school name":"Northeast High School","salary":88000,"favorite animal":"Dog"},"8":{"first_name":"Jacob","last_name":"Thomas","age":19,"address":"753 Pine St","country":"Australia","school name":"Southeast High School","salary":30000,"favorite animal":"Monkey"},"9":{"first_name":"Ava","last_name":"Lee","age":38,"address":"258 Elm St","country":"Canada","school name":"Southwest High School","salary":67000,"favorite animal":"Penguin"},"10":{"first_name":"Noah","last_name":"Gonzalez","age":27,"address":"456 Oak Ln","country":"USA","school name":"Central High School","salary":59000,"favorite animal":"Dolphin"},"11":{"first_name":"Charlotte","last_name":"Hernandez","age":43,"address":"753 Pine St","country":"Australia","school name":"North High School","salary":75000,"favorite animal":"Horse"},"12":{"first_name":"Ethan","last_name":"Moore","age":34,"address":"321 Maple Ave","country":"Canada","school name":"East High School","salary":62000,"favorite animal":"Giraffe"},"13":{"first_name":"Luna","last_name":"Jackson","age":29,"address":"789 Elm St","country":"USA","school name":"West High School","salary":56000,"favorite animal":"Koala"},"14":{"first_name":"Liam","last_name":"Martin","age":21,"address":"654 Pine Rd","country":"Canada","school name":"Northwest High School","salary":42000,"favorite animal":"Panda"},"15":{"first_name":"Avery","last_name":"Thompson","age":47,"address":"987 Oak St","country":"USA","school name":"Southeast High School","salary":88000,"favorite animal":"Tiger"},"16":{"first_name":"Logan","last_name":"White","age":33,"address":"159 Maple St","country":"Australia","school name":"Northeast High School","salary":67000,"favorite animal":"Elephant"},"17":{"first_name":"Chloe","last_name":"Allen","age":50,"address":"753 Pine St","country":"Canada","school name":"Southwest High School","salary":93000,"favorite animal":"Dolphin"},"18":{"first_name":"James","last_name":"Wright","age":25,"address":"258 Elm St","country":"USA","school name":"Central High School","salary":55000,"favorite animal":"Lion"},"19":{"first_name":"Grace","last_name":"King","age":36,"address":"456 Oak Ln","country":"Australia","school name":"East High School","salary":71000,"favorite animal":"Penguin"},"20":{"first_name":"Alexander","last_name":"Scott","age":52,"address":"321 Maple Ave","country":"Canada","school name":"Northwest High School","salary":78000,"favorite animal":"Gorilla"},"21":{"first_name":"Hazel","last_name":"Green","age":48,"address":"789 Elm St","country":"USA","school name":"West High School","salary":84000,"favorite animal":"Kangaroo"},"22":{"first_name":"Benjamin","last_name":"Baker","age":39,"address":"654 Pine Rd","country":"Canada","school name":"Southeast High School","salary":63000,"favorite animal":"Panda"},"23":{"first_name":"Sofia","last_name":"Nelson","age":22,"address":"987 Oak St","country":"USA","school name":"Northeast High School","salary":48000,"favorite animal":"Turtle"},"24":{"first_name":"Michael","last_name":"Williams","age":19,"address":"159 Maple St","country":"Australia","school name":"Southwest High School","salary":30000,"favorite animal":"Koala"},"25":{"first_name":"Madison","last_name":"Jones","age":44,"address":"753 Pine St","country":"USA","school name":"Central High School","salary":76000,"favorite animal":"Monkey"},"26":{"first_name":"Daniel","last_name":"Davis","age":30,"address":"258 Elm St","country":"Canada","school name":"North High School","salary":57000,"favorite animal":"Tiger"},"27":{"first_name":"Claire","last_name":"Rodriguez","age":37,"address":"456 Oak Ln","country":"Australia","school name":"East High School","salary":69000,"favorite animal":"Giraffe"},"28":{"first_name":"Miles","last_name":"Parker","age":26,"address":"789 Elm St","country":"USA","school name":"West High School","salary":54000,"favorite animal":"Penguin"},"29":{"first_name":"Audrey","last_name":"Gomez","age":24,"address":"321 Maple Ave","country":"Canada","school name":"Northwest High School","salary":50000,"favorite animal":"Lion"},"30":{"first_name":"Henry","last_name":"Cruz","age":41,"address":"654 Pine Rd","country":"USA","school name":"Southeast High School","salary":65000,"favorite animal":"Dolphin"},"31":{"first_name":"Penelope","last_name":"Collins","age":32,"address":"987 Oak St","country":"Australia","school name":"Northeast High School","salary":75000,"favorite animal":"Gorilla"},"32":{"first_name":"Sebastian","last_name":"Perez","age":28,"address":"159 Maple St","country":"Canada","school name":"Southwest High School","salary":61000,"favorite animal":"Elephant"},"33":{"first_name":"Ella","last_name":"Turner","age":33,"address":"753 Pine St","country":"USA","school name":"Central High School","salary":62000,"favorite animal":"Turtle"},"34":{"first_name":"Jacob","last_name":"Adams","age":49,"address":"258 Elm St","country":"Australia","school name":"North High School","salary":91000,"favorite animal":"Panda"},"35":{"first_name":"Mia","last_name":"Campbell","age":23,"address":"456 Oak Ln","country":"Canada","school name":"East High School","salary":48000,"favorite animal":"Tiger"},"36":{"first_name":"William","last_name":"Mitchell","age":40,"address":"789 Elm St","country":"USA","school name":"West High School","salary":67000,"favorite animal":"Kangaroo"},"37":{"first_name":"Victoria","last_name":"Parker","age":28,"address":"321 Maple Ave","country":"Australia","school name":"Northwest High School","salary":57000,"favorite animal":"Monkey"},"38":{"first_name":"Owen","last_name":"Evans","age":31,"address":"654 Pine Rd","country":"Canada","school name":"Southeast High School","salary":52000,"favorite animal":"Gorilla"},"39":{"first_name":"Natalie","last_name":"Edwards","age":47,"address":"987 Oak St","country":"USA","school name":"Northeast High School","salary":83000,"favorite animal":"Penguin"},"40":{"first_name":"Carter","last_name":"Collins","age":19,"address":"159 Maple St","country":"Australia","school name":"Southwest High School","salary":32000,"favorite animal":"Lion"},"41":{"first_name":"Scarlett","last_name":"Stewart","age":44,"address":"753 Pine St","country":"USA","school name":"Central High School","salary":80000,"favorite animal":"Dolphin"},"42":{"first_name":"Gabriel","last_name":"Sanchez","age":25,"address":"258 Elm St","country":"Canada","school name":"North High School","salary":51000,"favorite animal":"Giraffe"},"43":{"first_name":"Aria","last_name":"Morales","age":30,"address":"456 Oak Ln","country":"Australia","school name":"East High School","salary":63000,"favorite animal":"Kangaroo"},"44":{"first_name":"Jackson","last_name":"Roach","age":39,"address":"789 Elm St","country":"USA","school name":"West High School","salary":75000,"favorite animal":"Tiger"},"45":{"first_name":"Amelia","last_name":"Bush","age":21,"address":"321 Maple Ave","country":"Canada","school name":"Northwest High School","salary":41000,"favorite animal":"Turtle"},"46":{"first_name":"Elijah","last_name":"Knight","age":35,"address":"654 Pine Rd","country":"USA","school name":"Southeast High School","salary":72000,"favorite animal":"Elephant"},"47":{"first_name":"Leah","last_name":"Hudson","age":46,"address":"987 Oak St","country":"Australia","school name":"Northeast High School","salary":81000,"favorite animal":"Lion"},"48":{"first_name":"William","last_name":"Roberts","age":33,"address":"159 Maple St","country":"Canada","school name":"Southwest High School","salary":60000,"favorite animal":"Panda"},"49":{"first_name":"Aaliyah","last_name":"Drake","age":29,"address":"753 Pine St","country":"USA","school name":"Central High School","salary":57000,"favorite animal":"Gorilla"},"50":{"first_name":"Oliver","last_name":"Reyes","age":26,"address":"258 Elm St","country":"Australia","school name":"North High School","salary":48000,"favorite animal":"Penguin"}}'